version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule::
      intervail: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "axios"
